#ifndef AST_CUSTOM_DEFS_H_INCLUDED
#define AST_CUSTOM_DEFS_H_INCLUDED


#define COBRA_CONF_FILE "cobra.conf"
#define COBRA_CONF_CAT "cobra"

#define CAS_CLIENT_DEFAULT_GRPC_CONNECTION_STRING ""
#define CAS_CLIENT_REQ_DEADLINE_MS 250
#define CDS_PUBLISH_DEFAULT_GRPC_CONNECTION_STRING "unix:/var/run/cds_relay.sock"
#define CMS_SERVER_DEFAULT_GRPC_SERVER_ADDR "[::]:3100"

#endif // AST_CUSTOM_DEFS_H_INCLUDED
